version: "3.8"

services:
  application:
    image: eclipse-temurin:17
    ports:
      - "8080:8080"
    volumes:
      - ./target/quarkus-app/:/opt/app/
    entrypoint: ["java", "-jar", "/opt/app/quarkus-run.jar"]